
- name: "Get csrf token"
  uri:
    url: 'http://{{ jenkins_master.host }}:{{ jenkins_master.port }}/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)'
    user: "{{ jenkins_admin_user }}"
    password: "{{ jenkins_admin_pass }}"
    force_basic_auth: yes
    return_content: yes
  register: crumb

- name: "Create credentials"
  uri:
    method: POST
    url: 'http://{{ jenkins_master.host }}:{{ jenkins_master.port }}/credentials/store/system/domain/_/createCredentials'
    user: "{{ jenkins_admin_user }}"
    password: "{{ jenkins_admin_pass }}"
    force_basic_auth: yes
    headers:
      Jenkins-Crumb: "{{ crumb.content.split(':')[1] }}"
    body: |
      json={
        "": "0",
        "credentials": {
          "scope": "GLOBAL",
          "id": "{{ ssh_cred.id }}",
          "username": "{{ ssh_cred.username }}",
          "password": "{{ ssh_cred.password }}",
          "description": "{{ ssh_cred.description }}",
          "$class": "com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl"
        }
      }
    follow_redirects: all
