
- name: Create user .ssh directory
  file:
    path: "{{ ssh_folder }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0700

- name: Deploy the known_hosts file
  copy:
    src: known_hosts
    dest: "{{ ssh_folder }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

- name: Deploy user public key
  copy:
    content: "{{ public_key }}"
    dest: "{{ ssh_folder }}/id_rsa.pub"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

- name: Deploy user private key
  copy:
    content: "{{ private_key }}"
    dest: "{{ ssh_folder }}/id_rsa"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0600
