
- name: Create user .ssh directory
  file:
    path: ~{{ username }}/.ssh
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0700

- name: Deploy user public key
  copy:
    content: "{{ public_key }}"
    dest: ~{{ username }}/.ssh/id_rsa.pub
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

- name: Deploy user private key
  copy:
    content: "{{ private_key }}"
    dest: ~{{ username }}/.ssh/id_rsa
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0600
